export type Status = 'NORMAL' | 'WARNING' | 'CRITICAL';

/** Output of AI Model 1 (sensor-based). */
export type SensorPrediction = 'HEALTHY' | 'WARNING' | 'DAMAGE' | 'CRITICAL';

/** Output of AI Model 2 (computer vision). */
export type ImageClass =
  | 'HEALTHY'
  | 'CRACK'
  | 'TEAR'
  | 'JOINT_DAMAGE'
  | 'EDGE_DAMAGE'
  | 'SEVERE_DAMAGE';

/** Combined sensor + image prediction. */
export type HealthPrediction = 'HEALTHY' | 'EARLY_DAMAGE' | 'WARNING' | 'CRITICAL_DAMAGE';

export type Severity = 'NONE' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/**
 * One reading from the backend / ESP32.
 * The first block matches the API example in the project brief.
 * Fields marked optional can be added by the backend when the models are ready.
 */
export interface Telemetry {
  rpm: number;
  temperature: number; // °C
  load: number; // kg
  vibration: number; // g (RMS)
  belt_health: number; // 0–100
  sensor_prediction: SensorPrediction;
  image_prediction: ImageClass;
  confidence: number; // 0–1, confidence of image_prediction
  overall_status: Status;

  timestamp?: number; // epoch ms; set by the client if missing
  health_prediction?: HealthPrediction;
  health_confidence?: number; // 0–1
  recommendation?: string;
  vibration_waveform?: number[]; // recent raw samples in g
}

export interface HistoryPoint {
  t: number;
  rpm: number;
  temperature: number;
  load: number;
  vibration: number;
}

/** Bounding box, normalised 0–1, origin at the top-left of the image. */
export interface BBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface Detection {
  label: ImageClass;
  confidence: number; // 0–1
  bbox: BBox;
}

export interface InspectionResult {
  condition: ImageClass;
  confidence: number; // 0–1
  detections: Detection[];
  /** "model" = real API response, "demo" = dummy result generated by the frontend. */
  source: 'model' | 'demo';
  analyzedAt: number;
}

export interface Capture {
  dataUrl: string;
  blob: Blob;
  width: number;
  height: number;
  source: 'camera' | 'sample';
  capturedAt: number;
}

export type InspectionState =
  | { status: 'idle' }
  | { status: 'analyzing' }
  | { status: 'done'; result: InspectionResult }
  | { status: 'error'; message: string };

export interface Alert {
  id: string;
  time: number; // epoch ms
  source: string;
  detection: string;
  severity: 'Warning' | 'Critical';
}

export type Scenario = 'normal' | 'warning' | 'critical';
